[dependencies]
chrono = "0.4.11"
reqwest = {version = "0.10.4", features = ["blocking", "json", "gzip"]}
serde_json = "1.0.52"
structopt = "0.3.14"

[package]
authors = ["Albert Tugushev <albert@tugushev.ru>"]
edition = "2018"
name = "social-media-search"
version = "0.1.0"
